kind: Pod
apiVersion: v1
metadata:
  name: resources 
spec:  
  containers: 
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      # limitsshouldbe atleast or more than requests i.e hard limit
      limits:
        cpu: "100m"
        memory: "128Mi"  
     